### ISSUE TITLE
just return the %PATH% on windows

### ISSUE THREAD

**Issue by mafintosh** [sindresorhus/shell-path#1]
i needed something like this last week so thanks for creating it :) instead of throwing when used on windows couldn't this just return `%PATH%`?

**Comment by silverwind** [comment]
@mafintosh does Windows suffer from an incomplete path in GUI apps too? I could see some trickery with `%COMSPEC%` if so.

**Comment by mafintosh** [comment]
@silverwind i'm not a windows expert so i'm not completely sure. not sure if cmd.exe has a similar concept of profile files where you edit the PATH

**Comment by silverwind** [comment]
`%PATH%` is set in the GUI in Windows, so I _think_ it applies everywhere.

I need to play with Electron sometimes :smile:
