### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ericbiewener** [sindresorhus/shell-path#11]
This simply isn't working for me when trying to run the application as a packaged app. I have tried putting the following code in both my main.js "electron" file (e.g. the one with Electron's `createWindow()` function), as well as the "client side" javascript that runs once the app launches:

```
const shellPath = require('shell-path');
process.env.PATH = shellPath.sync();
```

I still don't end up with the right `$PATH` variable when executing future shell scripts.

**Comment by sindresorhus** [comment]
What did you get? What did you expect? Operating system? Etc.

**Comment by ericbiewener** [comment]
I'm trying to execute the shell script `brew install taglib` (using `child_process.exec`), but I get the error that the `brew` command cannot be found. Similarly, using `exec` to run `gem list` doesn't return the gems I have installed in my rvm-managed version of ruby.

My full path should look like:

```
/Users/ericbiewener/.rvm/gems/ruby-2.3.0/bin:/Users/ericbiewener/.rvm/gems/ruby-2.3.0@global/bin:/Users/ericbiewener/.rvm/rubies/ruby-2.3.0/bin:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin:/Users/ericbiewener/Repos/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/ericbiewener/.rvm/bin
```

When logging the results of `shellPath.sync()` from `main.js`, I get the following:

```
/usr/bin:/bin:/usr/sbin:/sbin:/Users/ericbiewener/.rvm/bin
```

When logging the results of `shellPath.sync()` in the client-side JS, I simply get undefined.

I'm on OS X 10.11.4

**Comment by ericbiewener** [comment]
And in case it helps, when running as a non-packaged app, I get the following output to my console when running `shellPath.sync()` (this occurs even if I don't try logging anything, but just call that method):

```
bash: no job control in this shell
exit
```

**Comment by sindresorhus** [comment]
Hmm, weird. You're using Bash, right?

**Comment by ericbiewener** [comment]
Yes. I came across this module today and am experiencing the same issue:

https://github.com/steelbrain/consistent-path

**Comment by sindresorhus** [comment]
Can you try running the following code in the packaged app and share the output:

``` js
require('child_process').execFileSync('/bin/bash', ['--version'], {encoding: 'utf8'})
```

``` js
require('child_process').execFileSync('/bin/bash', ['-ic', 'env'], {encoding: 'utf8'})
```

``` js
require('child_process').execFileSync('/bin/bash', ['-ic', 'echo $PATH'], {encoding: 'utf8'})
```

**Comment by silverwind** [comment]
Also might help to know where these paths are defined in your dotfiles.

**Comment by ericbiewener** [comment]
The output of those three, in order:

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

```
(I removed a few items here that didn't seem relevant and that had the word "private" in them)

SHELL=/bin/bash
TMPDIR=/var/folders/cq/bg8lr0dn3v91kzxnhgk8jf640000gn/T/
USER=ericbiewener
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/Users/ericbiewener/.rvm/bin
PWD=/
XPC_FLAGS=0x0
XPC_SERVICE_NAME=com.electron.bowie.194592
SHLVL=1
HOME=/Users/ericbiewener
LOGNAME=ericbiewener
_=/usr/bin/env
```

```
/usr/bin:/bin:/usr/sbin:/sbin:/Users/ericbiewener/.rvm/bin
```

In regards to where the desired paths are defined in my dotfiles:

_.bash_profile_
- /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin
- /Users/ericbiewener/Repos/venv/bin

_.bash_rc_
- /Users/ericbiewener/.rvm/bin

Not sure where the `...rvm/gems...` paths are defined, but I could probably figure that out from the RVM website if necessary.

**Comment by ericbiewener** [comment]
Not sure if it helps, but I get the same result even if I try running a bash file via `execFile` and include the shebang `#!/usr/bin/env bash` at the top. I had hoped that this would cause the correct environment to get pulled in, but no dice.

**Comment by sindresorhus** [comment]
I was tipped about [`path_helper`](http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper) today. Seems like it handles more cases.

@ericbiewener Mind running this in a packaged app?

``` js
require('child_process').execFileSync('/usr/libexec/path_helper', {encoding: 'utf8'})
```

**Comment by sindresorhus** [comment]
// @adam-moss  ⬆️ Can you too?

**Comment by adam-moss** [comment]
@sindresorhus  `console.log(require('child_process').execFileSync('/usr/libexec/path_helper', {encoding: 'utf8'}));` in Atom gives me:

```
VM2003:2 PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/adam.moss/GitHub/ansible/bin:/Users/adam.moss/.nvm/versions/node/v6.2.2/bin"; export PATH;
MANPATH="/usr/share/man:/usr/local/share/man:/Users/adam.moss/GitHub/ansible/docs/man:/Users/adam.moss/.nvm/versions/node/v6.2.2/share/man:/Library/Developer/CommandLineTools/usr/share/man"; export MANPATH;
undefined
```

`echo $PATH` for comparison:

```
/Users/adam.moss/GitHub/ansible/bin:/Users/adam.moss/.nvm/versions/node/v6.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Regards

**Comment by ericbiewener** [comment]
@sindresorhus It gave me:

`PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"; export PATH;`

**Comment by sindresorhus** [comment]
Thanks @adam-moss. So it seems `path_helper` would at least solve #6.

**Comment by sindresorhus** [comment]
@ericbiewener Hmm, still no dice. Maybe we can just hard-code some paths in https://github.com/sindresorhus/fix-path

**Comment by silverwind** [comment]
`path_helper` is used in `/etc/profile`, which in turn should be sourced by all shells. I'd not be opposed to us enriching our paths array with paths from `path_helper`.

**Comment by silverwind** [comment]
I updated shell-env (https://github.com/sindresorhus/shell-env/commit/c704d617e2515e5d70c1cb496bb9a519643270c9) to use `-l` to obtain a login shell, which in turn should lead to `/etc/profile` being sourced. @ericbiewener can you verify if this is fixed by reinstalling the module?

**Comment by silverwind** [comment]
I'll close this off as I'm pretty certain above update has fixed this issue.
