### ISSUE TITLE
Getting error on module.exports = () => shellEnv().then(x => x.PATH)

### ISSUE THREAD

**Issue by vishalsh-spec** [sindresorhus/shell-path#12]
Please find attached image for information.

![running node command](https://cloud.githubusercontent.com/assets/6346780/15244513/20412784-191f-11e6-8acc-627493f4be6d.png)

**Comment by sindresorhus** [comment]
Upgrade your Node.js version.

https://github.com/sindresorhus/shell-path/blob/b9b651ce6bde298561c9378a24590b74571582f3/package.json#L16
