### ISSUE TITLE
Force interactive shell for common shells

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/shell-path#3]
Spawned by https://github.com/sindresorhus/fix-path/issues/3

To handle cases like where zsh users wrongly put PATH modifications into `.zshrc` instead of `zshenv`, we should consider using the `-i` flag to force an interactive shell to obtain the full `PATH`.

What needs to be done is to investigate which shells have an `-i` flag or similar.

**Comment by sindresorhus** [comment]
Hah, I was just going to open this issue. Definitely.

**Comment by silverwind** [comment]
bash, zsh, dash, fish come to mind as popular shells, anything else you'd see worth investigating?

**Comment by sindresorhus** [comment]
`sh`

**Comment by sindresorhus** [comment]
Thanks @silverwind :D

**Comment by silverwind** [comment]
Looks `-i`is ubiquitous to all five tested shells, so I went ahead and changed it. With my pretty heavy `.zshrc` it increased the execution time of that `execFile` quite a bit, but I say it's worth it for accuracy.

**Comment by sindresorhus** [comment]
Definitely worth it. Even I initially my environment variables in `.zshrc`.

**Comment by sindresorhus** [comment]
@silverwind I owe you many times. Let me know whenever you would like some feedback/brainstorming on anything at all ;)

**Comment by silverwind** [comment]
Happy to help. I'll make sure to use your `ama` if anything comes to mind :wink:
