### ISSUE TITLE
/usr/local/bin not included in returned path

### ISSUE THREAD

**Issue by adam-moss** [sindresorhus/shell-path#6]
Hi,
I've been working with @steelbrain to resolve an issue with an invalid path being returned in OSX in atom (specifically the linter-puppet-lint package, by way of atom-linter, consistent-path, and ultimately shell-path).
Whilst it picks up the path including entries from .bashrc (in my case nvm), the result of .sync doesn't seem to be including /usr/local/bin.
Actual path: /Users/user.name/.nvm/versions/node/v5.3.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
shell-path: /Users/user.name/.nvm/versions/node/v5.3.0/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by steelbrain** [comment]
Worked around in consistent-path in https://github.com/steelbrain/consistent-path/pull/2

**Comment by sindresorhus** [comment]
How do you you set `/usr/local/bin` as a PATH?

**Comment by adam-moss** [comment]
`/usr/local/bin` is a default path in OSX, it's defined in `/etc/paths`:
`/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin`

**Comment by silverwind** [comment]
It's rather odd that such a core system path is missing. Can you post the output of these commands?

```
$ echo $SHELL
$ dscl . -read /Users/$(whoami) UserShell
$ $(dscl . -read /Users/$(whoami) UserShell | cut -f2 -d" ") --version
$ sw_vers -productVersion
$ electron --version
```

**Comment by adam-moss** [comment]
```
$ /bin/bash
$ UserShell: /bin/bash
$ GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
$ 10.11.2
$ -bash: electron: command not found
```

(for the last I presume this is buried somewhere in the Atom package for OSX, and not exposed directly).

**Comment by silverwind** [comment]
@Adam-Moss thanks, pretty recent versions. Let's see what the various methods to obtain the path return:

```
$ sudo -Hiu $(whoami) 'echo "$PATH"'
$ /bin/bash -i -c 'echo "$PATH"'
$ echo $PATH
```

**Comment by adam-moss** [comment]
@silverwind here you go:

```
$ /Users/user.name/.nvm/versions/node/v5.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ /Users/user.name/.nvm/versions/node/v5.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
$ /Users/user.name/.nvm/versions/node/v5.4.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by silverwind** [comment]
Thanks. The cause must be either a bug in Electron or something fundamental about GUI apps we're missing.

**Comment by silverwind** [comment]
https://github.com/sindresorhus/shell-env/commit/c704d617e2515e5d70c1cb496bb9a519643270c9 likely fixed this, please reopen if it still persists.
