### ISSUE TITLE
latest techniques still not working in electron sadly

### ISSUE THREAD

**Issue by max-mapper** [sindresorhus/shell-path#7]
in an electron 0.36.4 app console (`sp` is `require('shell-path')`):

<img width="540" alt="screen shot 2016-01-19 at 3 08 15 pm" src="https://cloud.githubusercontent.com/assets/39759/12434901/b140ee06-bebe-11e5-92c2-ddd7605e10bb.png">

whereas `sudo -Hiu max "echo $PATH"` returns the wrong thing, `sudo -Hiu max env` has my correct PATH in it

**Comment by max-mapper** [comment]
heres my current hack

``` js
// HACK
try {
  var env = require('child_process').execSync('sudo -Hiu ' + process.env.USER + ' env').toString()
} catch (e) {}

if (env) {
  var envPath
  var lines = env.split('\n').forEach(function (l) {
    if (l.indexOf('PATH=') === 0) envPath = l.split('PATH=')[1]
  })
  if (envPath) process.env.PATH = process.env.PATH + ':' + envPath
}
```

**Comment by silverwind** [comment]
These issues are so weird :cry: I cannot reproduce any of them here (latest everything). I get all zsh paths with any of the methods, then chsh'd to bash, still working:
![screen shot 2016-01-20 at 12 30 17 am](https://cloud.githubusercontent.com/assets/115237/12435307/11b68496-bf0d-11e5-9dc7-ef1e5b337c63.png)

Might as well include that env hack unless someone has a better idea.

**Comment by max-mapper** [comment]
oh yea i should have mentioned it only happens when running from a packaged app (electron-packager), when launched from the CLI it works for me too

also I ended up writing this module just now just so I could get my app working https://github.com/maxogden/user-env

**Comment by silverwind** [comment]
Oh, of course. I tried in a packaged app and saw the issue. Interestingly, both the sudo+echo and sudo+env method return a rather short path for me, while shell+echo also included paths from `~/.zshenv`.

I'd say we replace the current sudo method with the env one.
