### ISSUE TITLE
Problem when shell startup prints a string

### ISSUE THREAD

**Issue by rbkreisberg** [sindresorhus/shell-path#8]
When a shell dotfile (eg. .bash_profile, .zshrc) prints directly to the terminal, the $PATH variable is incorrectly read as the string printed by the dotfile.

Repro steps from command line:
1. `echo "yo!" >> .zshrc`
2. `zsh -i -c 'echo "$PATH"'`

The shell type (bash, etc) doesn't matter.  The bug only surfaces when this technique results in the "longest" version of $PATH

**Comment by rbkreisberg** [comment]
I see that `-i` creates an interactive shell.  Is this necessary?  

If I drop it, I see the correct value for $PATH without the string echoed by the shell dotfile.

**Comment by silverwind** [comment]
`-i` is necessary at least on my machine, or otherwise paths from `.zshrc` are missing. It's a hack, but we could remove all lines except the last one, hmm.

**Comment by rbkreisberg** [comment]
Right on.  Thanks much.

**Comment by silverwind** [comment]
Released in 1.0.8!
