### ISSUE TITLE
Remove `sudo` check

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/shell-path#9]
In https://github.com/sindresorhus/shell-path/commit/8522076328e0b13874b234075f6a50a4a6084424, I replaced the normal check with [`shell-env`](https://github.com/sindresorhus/shell-env), which now instead of `$ echo $PATH`, parses out the PATH from `$ env`, same as the `sudo` check does. I'm doubtful how useful the `sudo` check is now. It actually misses some things, like `.zshrc`, since it doesn't run the shell interactively.

Need to ensure it still works fine in a packaged app without `sudo`.
## 

@silverwind What do you think?

**Comment by silverwind** [comment]
I'm fine with plain `env` if it works. Maybe @maxogden can give it a try?

**Comment by max-mapper** [comment]
Just tested in electron (the only place where I have issues getting the path) and both the `sudo -Hiu` technique and `$ env` return the correct `PATH`, so I'm fine with this. I want to note that using `sudo` in this way does not require superuser privileges, and the advantage of it over using `$ env` is that you can get the environment for any user, not just the current user (not relevant here).

**Comment by sindresorhus** [comment]
:+1: Cool. Thanks for testing Max :)

**Comment by silverwind** [comment]
Thanks! I've been seeing `sudo` fail on CI with `must be setuid root` errors which points to a permission error on `/usr/bin/sudo`, so I'm kind of glad it's gone.
